export const SAVE_USER_INFO = "SAVE_USER_INFO";
export const SAVE_USER_INFO_SUCCESS = "SAVE_USER_INFO_SUCCESS";
export const SAVE_USER_INFO_ERROR = "SAVE_USER_INFO_ERROR";
export const CLEAN_STORE = "CLEAN_STORE";

// Layout
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
